### ISSUE TITLE
Extra line added when saving without markup and loading back in

### ISSUE THREAD

**Issue by lspector** [JonyEpsilon/gorilla-repl#286]
Saving without markup and then loading back in adds an extra newline at the end. These accumulate over time, and even the first one generates unhelpful git diffs.

**Comment by benfb** [comment]
Got a fix for this! I'll release a patch version in not too long.

**Comment by lspector** [comment]
If I make a new project with `lein new gorilla-app foo` then the resulting project still exhibits the problem. Do I have to be doing something different? Can the fix be made to work with this procedure?

**Comment by benfb** [comment]
I hadn't released 0.5.2 yet :) That command should work now, I just pushed out the release.

**Comment by lspector** [comment]
Still getting:

```
  :plugins [[org.clojars.benfb/lein-gorilla "0.5.1"]]
```

in the `project.clj` that I get from `lein new gorilla-app foo`...
